### ISSUE TITLE
groovy file modification

### ISSUE THREAD

**Issue by joleneyue** [nadiadavidson/necklace#17]
dear developer,

i would like to ask you if i run without the raw reads, instead i use the genome_guided_assembly and de_novo_assembly as the input file, how one can modify the necklace.groovy file to this way? because now the groovy file is designed in a way using the raw reads.

could you kindly provide a new necklace.groovy file for the stringtie and trinity assembly as input files.

Thanks a lot.
Cheers,
Yuling

**Comment by nadiadavidson** [comment]
Hi Yuling,
You can use the options described here, https://github.com/Oshlack/necklace/wiki/Options 
Note that Necklace still expects some raw reads to run, but you can pass it any for the species and it won't use these for anything apart from gene expression quantification towards the end of the pipeline.
Let me know if you have any further questions.
Cheers,
Nadia.

**Comment by joleneyue** [comment]
dear Nadia,

thanks for your reply.

i added the stringtie and trinity assembly in the configure file: 
//The denovo trinity assembly
de_novo_assembly_file="seqtk_complete_trinity.fa"

//The genome guided assembly 
genome_guided_assembly_file="transcript_hints_stringtie.gtf"

also i add these into the necklace.groovy file at the top: 

de_novo_assembly_file="seqtk_complete_trinity.fa"
genome_guided_assembly_file="transcript_hints_stringtie.gtf"

the necklace will still run the hisat2 and mapping reads step for the stringtie.  necklace does not run trinity again.

do you know the reason of this?

Cheers,
Yuling
