### ISSUE TITLE
Passing a genome-guided Trinity assembly to necklace

### ISSUE THREAD

**Issue by flopezo** [nadiadavidson/necklace#2]
Hello,

I was wondering if it is possible to pass _de novo_ and genome-guided `Trinity` assemblies in FASTA format and a `StringTie` assembly to `necklace`. I have pre-generated assemblies and am interested in using the recently added `necklace` options `de_novo_assembly_file` and `genome_guided_assembly_file`. 

Any help is greatly appreciated!

**Comment by nadiadavidson** [comment]
Hi, yes this should be possible. I give a short description at https://github.com/Oshlack/necklace/wiki/Options but let me know if you need further information. If you have mutiple fasta assemblies, you should combine them into a single fasta file and pass that as the de_novo_assembly_file parameter.

**Comment by MFlores2021** [comment]
Hello,
I am passing de novo assembly with the de_novo_assembly_file parameter, but Necklace still expects reads_R1 and reads_R2 to be provided.  How to avoid this?
best,

Mirella

**Comment by nadiadavidson** [comment]
You will still need to provide the read files. These are used for the genome-guided assembly (unless you also pass a pre-assembled .gtf file), and also used to obtain the read counts (which you can use for differential expression analysis) and for reporting some information about the superTranscriptome assembly.

**Comment by MFlores2021** [comment]
Is possible to provide fasta reads?
Thanks!

**Comment by nadiadavidson** [comment]
No, unfortunately not at this stage. But I'll keep it in mine for future versions!
