### ISSUE TITLE
FAILED at the beginning of pipeline

### ISSUE THREAD

**Issue by ghost** [nadiadavidson/necklace#8]
I ran the  first command and I got the follow:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (file:/home/cesarihv7/superTranscriptome/necklace-1.01/tools/bpipe-0.9.9.2/bin/../lib/bpipe.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
====================================================================================================
|                              Starting Pipeline at 2019-06-12 00:19                               |
====================================================================================================

========================================= Stage set_input ==========================================
ERROR: Expected output file <path>/<sample_1_read_end_1>.fastq.gz could not be found 

========================================= Pipeline Failed ==========================================

Expected output file <path>/<sample_1_read_end_1>.fastq.gz could not be found

Use 'bpipe errors' to see output from failed commands.

root@instance-1-lev820:/home/cesarihv7/superTranscriptome/necklace-1.01# exit

**Comment by nadiadavidson** [comment]
Hi, 
What command did you run? and what is the contents of your configuration file?
It looks like you need to replace " /<sample_1_read_end_1>.fastq.gz" with the path and name of your file.
Cheers,
Nadia.
